/* ---------------------------------------------------------------------------
   Component: RootLayout
   Purpose:
     - Defines the root layout structure for the entire Next.js application.
     - Applies global styles, fonts, authentication provider, and app-wide 
       utilities like toast notifications.
   Imports:
     - Metadata type from Next.js for SEO settings.
     - Global styles (globals.css).
     - DM Sans font from Google Fonts.
     - Providers: Custom wrapper for global state or theming.
     - ClerkProvider: Manages authentication and user sessions.
     - Toaster (sonner): For toast notifications across the app.
   Font:
     - DM Sans loaded with `display: swap` for better performance.
     - Stored as a CSS variable `--font-dm-sans`.
   Metadata:
     - title: Default page title.
     - description: Default meta description.
   Layout Flow:
     1. Wraps the entire app in ClerkProvider for authentication context.
     2. Uses <html> with lang="en".
     3. Applies DM Sans font to <body>.
     4. Wraps children inside a `.root-layout` div.
     5. Includes Providers component for global context/state.
     6. Adds Toaster for global toast messages.
--------------------------------------------------------------------------- */

import type { Metadata } from "next"; // SEO metadata type
import "./globals.css"; // Global styles
import { DM_Sans } from "next/font/google"; // Google font loader
import Providers from "./providers"; // Custom global providers (theme, state, etc.)
import { ClerkProvider } from "@clerk/nextjs"; // Auth provider
import { Toaster } from "sonner"; // Toast notifications

// Load and configure DM Sans font
const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

// Default site metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Authentication context provider
    <ClerkProvider>
      <html lang="en">
        {/* Apply DM Sans font globally */}
        <body className={`${dmSans.className}`}>
          {/* Global providers (state, theme, etc.) */}
          <Providers>
            {/* Main app container */}
            <div className="root-layout">{children}</div>
            {/* Global toast notifications */}
            <Toaster richColors closeButton />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
